name: qgss-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # A versão específica do Python que você deseja usar
  - pip
  - numpy=2.3.1
  - scipy=1.16.0
  - matplotlib=3.10.3
  - pandas
  - sympy=1.14.0
  - networkx=3.2.1  # Versão ajustada conforme detectado nas instalações existentes
  - seaborn=0.13.2
  - pillow=11.3.0
  - pyarrow=18.1.0
  - dill=0.4.0
  - tqdm=4.67.1
  - jupyterlab=4.4.4
  - jupyter=1.1.1
  - ipywidgets
  - pip:
    - "qiskit==2.1.1"
    - "qiskit-ibm-runtime==0.40.0"
    - "qiskit-aer==0.17.1" 
    # Instalar primeiro o qc-grader que vai resolver as dependências
    - "qc-grader[jupyter,qiskit] @ git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git"
    # Depois instalar o qiskit-ibm-catalog com versão compatível
    - "qiskit-ibm-catalog>=0.8.0"
    - "pylatexenc"
    - "pydot==4.0.1"
    - "pyscf==2.9.0"
    - "stevedore==5.4.1"
    - "rustworkx==0.16.0"
    - "symengine==0.13.0"
    - "requests==2.32.3"
    - "requests-ntlm==1.3.0"
    - "urllib3==2.5.0"
    - "ibm-platform-services==0.66.1"
    - "ibm_cloud_sdk_core==3.24.1"
    - "python-dateutil==2.9.0.post0"
    - "cryptography==45.0.5"
