name: qgss-2025-alt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=2.3.1
  - scipy=1.16.0
  - matplotlib=3.10.3
  - pandas
  - sympy=1.14.0
  - networkx=3.2.1
  - seaborn=0.13.2
  - pillow=11.3.0
  - pyarrow=18.1.0
  - dill=0.4.0
  - tqdm=4.67.1
  - jupyterlab=4.4.4
  - jupyter=1.1.1
  - ipywidgets
  - ipykernel
  - pip:
    - "qiskit>=2.1.0,<2.2.0"
    - "qiskit-ibm-runtime>=0.40.0,<0.41.0"
    - "qiskit-aer>=0.17.0,<0.18.0"
    - "qc-grader[jupyter,qiskit] @ git+https://github.com/qiskit-community/Quantum-Challenge-Grader.git"
    - "qiskit-ibm-catalog>=0.8.0"
    - "pylatexenc"
    - "pydot>=4.0.0"
    - "pyscf>=2.9.0"
    - "stevedore>=5.4.0"
    - "rustworkx>=0.16.0"
    - "symengine>=0.13.0"
